from reportlab.lib.pagesizes import letter
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)
from reportlab.lib.styles import getSampleStyleSheet


def generate_report(insights, output_path):
    """
    Generate PDF report from analysis insights
    """

    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter
    )

    styles = getSampleStyleSheet()

    content = []

    content.append(
        Paragraph(
            "AI Data Analysis Report",
            styles["Title"]
        )
    )

    content.append(Spacer(1, 20))

    content.append(
        Paragraph(
            "Generated by AI Data Analyst Agent",
            styles["Normal"]
        )
    )

    content.append(Spacer(1, 20))

    content.append(
        Paragraph(
            "Key Insights:",
            styles["Heading2"]
        )
    )

    for key, value in insights.items():

        text = f"{key.replace('_', ' ').title()}: {value}"

        content.append(
            Paragraph(
                text,
                styles["Normal"]
            )
        )

        content.append(
            Spacer(1, 10)
        )

    doc.build(content)

    print(f"📄 Report generated: {output_path}")